lexik_jwt_authentication:
    secret_key: '%env(APP_SECRET)%'
    encoder:
        service:            lexik_jwt_authentication.encoder.lcobucci
        signature_algorithm: HS256
    user_id_claim: username